version: '2'
services:
  web:
    container_name: nodejs-ts-docker
    build: .
    command: yarn start
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - "9000:9000"
      - "9229:9229"
#    depends_on:
#      - postgres
#    environment:
#      DATABASE_URL: postgres://todoapp@postgres/todos
